### ISSUE TITLE
npm install error on Raspbian Buster 13-Feb-2020 armhf (RPi 3B+)

### ISSUE THREAD

**Issue by AusMatt** [gordonlkc/mqtt-get-lora-data#1]
Gordon,

Freshly installed Raspbian Buster 13-Feb-2020 with all updates on a RPi 3B+ has an npm install failure:

```
$ npm install
npm WARN mqtt_get_lora_data@1.0.0 No repository field.

audited 392 packages in 3.861s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ npm fund
mqtt_get_lora_data@1.0.0
└─┬ glob@7.1.6
  └── url: https://github.com/sponsors/isaacs
```

Do you know why?

Matt

**Comment by AusMatt** [comment]
I understand what this means now.
It's a warning, not an error!

**Comment by gordonlkc** [comment]
`npm` decided to add a new command: `npm fund` that will provide more visibility to npm users on what dependencies are actively looking for ways to fund their work. 

The install stage seems success 😄 try to run the program with `node index.js`

**Comment by AusMatt** [comment]
Thanks Gordon,

I should have Googled before posting the issue!

Matt

**Comment by gordonlkc** [comment]
All good! I was surprised when I first saw that message also
